# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser_info.proto\x12\x07\x65xample\"\x1b\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x0cUserResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2N\n\x0bUserService\x12?\n\x0egetUserAddress\x12\x14.example.UserRequest\x1a\x15.example.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=28
  _globals['_USERREQUEST']._serialized_end=55
  _globals['_USERRESPONSE']._serialized_start=57
  _globals['_USERRESPONSE']._serialized_end=103
  _globals['_USERSERVICE']._serialized_start=105
  _globals['_USERSERVICE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
